/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oriahulrich_perusalwithspritz_MainActivity */

#ifndef _Included_com_oriahulrich_perusalwithspritz_MainActivity
#define _Included_com_oriahulrich_perusalwithspritz_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_oriahulrich_perusalwithspritz_MainActivity_CAPTURE_IMAGE_ACTIVITY_REQUEST_CODE
#define com_oriahulrich_perusalwithspritz_MainActivity_CAPTURE_IMAGE_ACTIVITY_REQUEST_CODE 100L
/*
 * Class:     com_oriahulrich_perusalwithspritz_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_oriahulrich_perusalwithspritz_MainActivity_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
