/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_perusecomposer_perusewithspritz_PeruseMainActivity */

#ifndef _Included_com_oriahulrich_perusalwithspritz_MainActivity
#define _Included_com_oriahulrich_perusalwithspritz_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_perusecomposer_perusewithspritz_PeruseMainActivity.h
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_oriahulrich_perusalwithspritz_MainActivity_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
