/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oriahulrich_perusalwithspritz_MainActivity_TextInputState */

#ifndef _Included_com_oriahulrich_perusalwithspritz_MainActivity_TextInputState
#define _Included_com_oriahulrich_perusalwithspritz_MainActivity_TextInputState
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
