/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_oriahulrich_perusalwithspritz_MainActivity.h"

/*
 * Class:     com_perusecomposer_perusewithspritz_PeruseMainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_oriahulrich_perusalwithspritz_MainActivity_getStringFromNative
  (JNIEnv *env, jobject obj)
  {
        return (*env)->NewStringUTF(env, "Hey from JNI ! ");
  }

